[platformio]
src_dir = .

[env:host01]
platform = espressif32@6.9.0
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
lib_deps =
    sandeepmistry/LoRa@0.8.0
    bblanchon/ArduinoJson@7.2.1
build_flags = -I .
build_src_filter = +<host01.ino*>
